site_name: Timeline
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  features:
    - navigation.footer
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: yellow
      accent: deep purple
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: yellow
      accent: deep orange

nav:
  - Home: index.md
  - About Me: about.md
  - Projects: projects.md
  - Skills: skills.md
  - Blog: 
      - All Posts: blog.md
      - Kubernetes Networking: blog/kubernetes-networking.md
      - Microservices in Go: blog/golang-microservices.md

  - Contact: contact.md
extra:
  tags:
    enabled: true
    index: blog.md  # The main blog page where all tagged posts will be listed

plugins:
  - search
  - tags

copyright: Copyright &copy; 2025 Laxman Patel
